trigger: none


parameters:
  - name: environment
    type: string
    default: dev

variables:
  - group: InsightFabric-TerraformAuth  # Secure SP credentials
  - name: env
    value: ${{ parameters.environment }}
  - name: workingDirectory
    value: 'learn-terraform-azure'
  - name: resource_group_name
    value: rg-${{ parameters.environment }}-insightfabric
  - name: keyvault_name
    value: kv-${{ parameters.environment }}-insightfabric
  - name: sqlserver_name
    value: sql-${{ parameters.environment }}-insightfabric
  - name: dotnetapp_name
    value: dotnetapp-${{ parameters.environment }}-insightfabric
  - name: azure-data-factory
    value: adf-${{ parameters.environment }}-insightfabric
  - name: function_app_name
    value: fn-${{ parameters.environment }}-insightfabric
  - name: log_analytics_workspace_name
    value: law-${{ parameters.environment }}-insightfabric
  - name: application_insights_name
    value: appi-${{ parameters.environment }}-insightfabric


pool:
  name: SelfHosted

stages:
  - stage: Terraform_Destroy
    displayName: 'Destroy Infrastructure with Terraform'
    jobs:
      - job: DestroyInfra
        displayName: 'Terraform Destroy'
        steps:
          - powershell: |
              Write-Host "Injecting SP credentials for Terraform destroy..."
              $env:ARM_CLIENT_ID = "$(servicePrincipalClientId)"
              $env:ARM_CLIENT_SECRET = "$(servicePrincipalClientSecret)"
              $env:ARM_SUBSCRIPTION_ID = "$(subscriptionId)"
              $env:ARM_TENANT_ID = "$(tenantId)"
              terraform init -reconfigure
              terraform destroy `
                -var "environment=$(env)" `
                -var "resource_group_name=$(resource_group_name)" `
                -var "keyvault_name=$(keyvault_name)" `
                -var "sqlserver-name=$(sqlserver_name)" `
                -var "dotnetapp-name=$(dotnetapp_name)" `
                -var "tenantid-devops=$(tenantId)" `
                -var "principalid-devops=$(principalid)"  `
                -var "azure-data-factory=$(azure-data-factory)" `
                -var "function_app_name=$(function_app_name)" `
                -var "log_analytics_workspace_name=$(log_analytics_workspace_name)" `
                -var "application_insights_name=$(application_insights_name)" `
                -auto-approve
            displayName: 'Terraform Destroy with SP Auth'
            workingDirectory: '$(workingDirectory)'
  

