table emotion_trend_daily
	lineageTag: 2d3c1d83-2ecc-4de8-884b-cb2bfb69a3df
	sourceLineageTag: [gold].[emotion_trend_daily]

	measure 'Avg Emotion Intensity' = ```
			AVERAGE(emotion_trend_daily[avg_emotion_score])
			       
			```
		lineageTag: 19d84e81-42fd-46b2-84ba-c32d7b207f05

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column event_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 403dbee5-e01c-4c8f-a1ee-e3f167ae53d0
		sourceLineageTag: event_date
		summarizeBy: none
		sourceColumn: event_date

		annotation SummarizationSetBy = Automatic

	column emotion_type
		dataType: string
		lineageTag: c68c42da-bf3f-4342-abcd-0fe5fe7847f1
		sourceLineageTag: emotion_type
		summarizeBy: none
		sourceColumn: emotion_type

		annotation SummarizationSetBy = Automatic

	column emotion_count
		dataType: int64
		formatString: 0
		lineageTag: 6408e055-5bef-45ce-8993-e0a521ec6523
		sourceLineageTag: emotion_count
		summarizeBy: sum
		sourceColumn: emotion_count

		annotation SummarizationSetBy = Automatic

	column avg_emotion_score
		dataType: double
		lineageTag: 58b990ae-776b-4a06-944e-500b886bda64
		sourceLineageTag: avg_emotion_score
		summarizeBy: sum
		sourceColumn: avg_emotion_score

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column emotion_percentage
		dataType: double
		lineageTag: d38ee4cf-1a81-4a3b-992f-bade1372e065
		sourceLineageTag: emotion_percentage
		summarizeBy: sum
		sourceColumn: emotion_percentage

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column event_dept_key
		dataType: string
		lineageTag: f628ab48-663c-456d-8e69-85f1558e0f97
		sourceLineageTag: event_dept_key
		summarizeBy: none
		sourceColumn: event_dept_key

		annotation SummarizationSetBy = Automatic

	column department_id
		dataType: int64
		formatString: 0
		lineageTag: d8c209af-fa96-48ce-bc53-56f13f9d307c
		sourceLineageTag: department_id
		summarizeBy: none
		sourceColumn: department_id

		annotation SummarizationSetBy = Automatic

	partition emotion_trend_daily = entity
		mode: directLake
		source
			entityName: emotion_trend_daily
			schemaName: gold
			expressionSource: 'DirectLake - LhInsightFabric'

