table gold_sentiment_daily
	lineageTag: c42d910b-2192-4b04-9f6c-7137fca0b493
	sourceLineageTag: [gold].[gold_sentiment_daily]

	measure 'Positive Sentiment %' =
			
			CALCULATE(
			    SUM(gold_sentiment_daily[sentiment_percentage]),
			    gold_sentiment_daily[sentiment_bucket] = "Positive"
			)
		lineageTag: d15407b8-74d3-4eae-9a26-610a38adb127

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Positive_Sentiment_7d = ```
			
			VAR LatestDate = MAX(gold_sentiment_daily[event_date])
			RETURN
			DIVIDE(
			    CALCULATE(
			        SUM(gold_sentiment_daily[sentiment_percentage]),
			        FILTER(
			            gold_sentiment_daily,
			            gold_sentiment_daily[sentiment_bucket] = "Positive"
			        ),
			        DATESINPERIOD(
			            gold_sentiment_daily[event_date],
			            LatestDate,
			            -7,
			            DAY
			        )
			    
			    ),
			     CALCULATE(
			        SUM(gold_sentiment_daily[sentiment_percentage]),
			        DATESINPERIOD(
			            gold_sentiment_daily[event_date],
			            LatestDate,
			            -7,
			            DAY
			        )
			    
			    )
			    
			
			)* 100
			```
		lineageTag: 167f5755-3ec8-4493-9d48-0495e32ab27b

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column event_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 176006b6-1ac2-47cd-9709-b446e5b576a6
		sourceLineageTag: event_date
		summarizeBy: none
		sourceColumn: event_date

		annotation SummarizationSetBy = Automatic

	column sentiment_bucket
		dataType: string
		lineageTag: 25b72869-afbf-4838-81da-3ec7047cbcfa
		sourceLineageTag: sentiment_bucket
		summarizeBy: none
		sourceColumn: sentiment_bucket

		annotation SummarizationSetBy = Automatic

	column sentiment_count
		dataType: int64
		formatString: 0
		lineageTag: fa62c251-d6c7-4990-b9b4-700af6b15168
		sourceLineageTag: sentiment_count
		summarizeBy: sum
		sourceColumn: sentiment_count

		annotation SummarizationSetBy = Automatic

	column sentiment_percentage
		dataType: double
		lineageTag: 7851752f-51b9-4850-8d1d-248e75717917
		sourceLineageTag: sentiment_percentage
		summarizeBy: sum
		sourceColumn: sentiment_percentage

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column net_sentiment_score
		dataType: double
		lineageTag: 374ebffa-dafd-48fc-ad82-36c51f1bdfe0
		sourceLineageTag: net_sentiment_score
		summarizeBy: sum
		sourceColumn: net_sentiment_score

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column event_dept_key
		dataType: string
		lineageTag: fc10eb8e-96fb-4c13-930d-6c6261d9a0a2
		sourceLineageTag: event_dept_key
		summarizeBy: none
		sourceColumn: event_dept_key

		annotation SummarizationSetBy = Automatic

	column department_id
		dataType: int64
		formatString: 0
		lineageTag: db3740e6-b9ae-405b-97ad-877f03d77075
		sourceLineageTag: department_id
		summarizeBy: none
		sourceColumn: department_id

		annotation SummarizationSetBy = Automatic

	partition gold_sentiment_daily = entity
		mode: directLake
		source
			entityName: gold_sentiment_daily
			schemaName: gold
			expressionSource: 'DirectLake - LhInsightFabric'

